// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor_test

import (
	"sync"

	"github.com/umputun/ralphex/pkg/processor"
)

// ReviewCheckpointStoreMock is a mock implementation of processor.ReviewCheckpointStore.
//
//	func TestSomethingThatUsesReviewCheckpointStore(t *testing.T) {
//
//		// make and configure a mocked processor.ReviewCheckpointStore
//		mockedReviewCheckpointStore := &ReviewCheckpointStoreMock{
//			LoadFunc: func() (processor.ReviewCheckpoint, bool, error) {
//				panic("mock out the Load method")
//			},
//			RemoveFunc: func() error {
//				panic("mock out the Remove method")
//			},
//			SaveFunc: func(reviewCheckpoint processor.ReviewCheckpoint) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedReviewCheckpointStore in code that requires processor.ReviewCheckpointStore
//		// and then make assertions.
//
//	}
type ReviewCheckpointStoreMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (processor.ReviewCheckpoint, bool, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func() error

	// SaveFunc mocks the Save method.
	SaveFunc func(reviewCheckpoint processor.ReviewCheckpoint) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// ReviewCheckpoint is the reviewCheckpoint argument value.
			ReviewCheckpoint processor.ReviewCheckpoint
		}
	}
	lockLoad   sync.RWMutex
	lockRemove sync.RWMutex
	lockSave   sync.RWMutex
}

// Load calls LoadFunc.
func (mock *ReviewCheckpointStoreMock) Load() (processor.ReviewCheckpoint, bool, error) {
	if mock.LoadFunc == nil {
		panic("ReviewCheckpointStoreMock.LoadFunc: method is nil but ReviewCheckpointStore.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedReviewCheckpointStore.LoadCalls())
func (mock *ReviewCheckpointStoreMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *ReviewCheckpointStoreMock) Remove() error {
	if mock.RemoveFunc == nil {
		panic("ReviewCheckpointStoreMock.RemoveFunc: method is nil but ReviewCheckpointStore.Remove was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc()
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedReviewCheckpointStore.RemoveCalls())
func (mock *ReviewCheckpointStoreMock) RemoveCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ReviewCheckpointStoreMock) Save(reviewCheckpoint processor.ReviewCheckpoint) error {
	if mock.SaveFunc == nil {
		panic("ReviewCheckpointStoreMock.SaveFunc: method is nil but ReviewCheckpointStore.Save was just called")
	}
	callInfo := struct {
		ReviewCheckpoint processor.ReviewCheckpoint
	}{
		ReviewCheckpoint: reviewCheckpoint,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(reviewCheckpoint)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedReviewCheckpointStore.SaveCalls())
func (mock *ReviewCheckpointStoreMock) SaveCalls() []struct {
	ReviewCheckpoint processor.ReviewCheckpoint
} {
	var calls []struct {
		ReviewCheckpoint processor.ReviewCheckpoint
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
