// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package processor_test

import (
	"sync"

	"github.com/umputun/ralphex/pkg/processor"
)

// RunRecordStoreMock is a mock implementation of processor.RunRecordStore.
//
//	func TestSomethingThatUsesRunRecordStore(t *testing.T) {
//
//		// make and configure a mocked processor.RunRecordStore
//		mockedRunRecordStore := &RunRecordStoreMock{
//			LoadFunc: func() (processor.RunRecord, bool, error) {
//				panic("mock out the Load method")
//			},
//			RemoveFunc: func() error {
//				panic("mock out the Remove method")
//			},
//			SaveFunc: func(runRecord processor.RunRecord) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedRunRecordStore in code that requires processor.RunRecordStore
//		// and then make assertions.
//
//	}
type RunRecordStoreMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (processor.RunRecord, bool, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func() error

	// SaveFunc mocks the Save method.
	SaveFunc func(runRecord processor.RunRecord) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// RunRecord is the runRecord argument value.
			RunRecord processor.RunRecord
		}
	}
	lockLoad   sync.RWMutex
	lockRemove sync.RWMutex
	lockSave   sync.RWMutex
}

// Load calls LoadFunc.
func (mock *RunRecordStoreMock) Load() (processor.RunRecord, bool, error) {
	if mock.LoadFunc == nil {
		panic("RunRecordStoreMock.LoadFunc: method is nil but RunRecordStore.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedRunRecordStore.LoadCalls())
func (mock *RunRecordStoreMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *RunRecordStoreMock) Remove() error {
	if mock.RemoveFunc == nil {
		panic("RunRecordStoreMock.RemoveFunc: method is nil but RunRecordStore.Remove was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc()
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedRunRecordStore.RemoveCalls())
func (mock *RunRecordStoreMock) RemoveCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *RunRecordStoreMock) Save(runRecord processor.RunRecord) error {
	if mock.SaveFunc == nil {
		panic("RunRecordStoreMock.SaveFunc: method is nil but RunRecordStore.Save was just called")
	}
	callInfo := struct {
		RunRecord processor.RunRecord
	}{
		RunRecord: runRecord,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(runRecord)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedRunRecordStore.SaveCalls())
func (mock *RunRecordStoreMock) SaveCalls() []struct {
	RunRecord processor.RunRecord
} {
	var calls []struct {
		RunRecord processor.RunRecord
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
